import type { Patient, Doctor, Appointment, Prescription } from './definitions';

export const patients: Patient[] = [
  {
    id: '1',
    name: 'Rohan Sharma',
    dateOfBirth: '20-05-1985',
    gender: 'Male',
    contact: 'rohan.sharma@example.com',
    address: '123 MG Road, Mumbai, India',
    medicalHistory: 'Hypertension, Allergic to Penicillin',
    avatarUrl: 'https://picsum.photos/seed/pat1/100/100',
  },
  {
    id: '2',
    name: 'Priya Patel',
    dateOfBirth: '15-08-1992',
    gender: 'Female',
    contact: 'priya.patel@example.com',
    address: '456 Park Street, Delhi, India',
    medicalHistory: 'Asthma',
    avatarUrl: 'https://picsum.photos/seed/pat2/100/100',
  },
  {
    id: '3',
    name: 'Arjun Singh',
    dateOfBirth: '30-11-1978',
    gender: 'Male',
    contact: 'arjun.singh@example.com',
    address: '789 Brigade Road, Bangalore, India',
    medicalHistory: 'Diabetes Type 2',
    avatarUrl: 'https://picsum.photos/seed/pat3/100/100',
  },
  {
    id: '4',
    name: 'Ananya Gupta',
    dateOfBirth: '10-02-2001',
    gender: 'Female',
    contact: 'ananya.gupta@example.com',
    address: '101 Mount Road, Chennai, India',
    medicalHistory: 'None',
    avatarUrl: 'https://picsum.photos/seed/pat4/100/100',
  },
  {
    id: '5',
    name: 'Vikram Reddy',
    dateOfBirth: '22-07-1965',
    gender: 'Male',
    contact: 'vikram.reddy@example.com',
    address: '212 Banjara Hills, Hyderabad, India',
    medicalHistory: 'High Cholesterol',
    avatarUrl: 'https://picsum.photos/seed/pat5/100/100',
  },
];

export const doctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Aditi Rao',
    specialty: 'Cardiologist',
    avatarUrl: 'https://picsum.photos/seed/doc1/100/100',
  },
  {
    id: '2',
    name: 'Dr. Vikram Singh',
    specialty: 'General Practitioner',
    avatarUrl: 'https://picsum.photos/seed/doc2/100/100',
  },
];

export const appointments: Appointment[] = [
  {
    id: '1',
    patientId: '1',
    doctorId: '1',
    date: new Date().toISOString().split('T')[0],
    time: '10:00',
    reason: 'Annual Checkup',
    status: 'Scheduled',
  },
  {
    id: '2',
    patientId: '2',
    doctorId: '2',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    time: '14:30',
    reason: 'Follow-up',
    status: 'Scheduled',
  },
  {
    id: '3',
    patientId: '3',
    doctorId: '1',
    date: new Date().toISOString().split('T')[0],
    time: '11:00',
    reason: 'Chest Pain',
    status: 'Scheduled',
  },
];

export const prescriptions: Prescription[] = [
  {
    id: '1',
    patientId: '1',
    doctorId: '1',
    medication: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once a day',
    startDate: '2023-01-10',
    endDate: null,
    refills: 6,
  },
  {
    id: '2',
    patientId: '2',
    doctorId: '2',
    medication: 'Albuterol Inhaler',
    dosage: '2 puffs',
    frequency: 'As needed for shortness of breath',
    startDate: '2022-06-01',
    endDate: null,
    refills: 12,
  },
  {
    id: '3',
    patientId: '3',
    doctorId: '1',
    medication: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice a day with meals',
    startDate: '2021-03-15',
    endDate: null,
    refills: 3,
  },
];
